### PR TITLE
Zoom Plugin skeleton app with user authentication

### PR DESCRIPTION
**Pull request by H4rsh4nk**
# 🔥 **Zoom Plugin Introduction**

- This is skeleton Zoom Meeting App
- Login/Signup with Username & Password to access the App
- Join Zoom Meeting as guest user with Meeting ID, Password and Username

> This app uses [Next App Router](https://nextjs.org/docs/app), [MongoDB](https://www.mongodb.com/) and [Next-Auth](https://next-auth.js.org/)
> To view deployment visit : https://zoomplugin.vercel.app/

---

## ⚡ **Installation**

1. Clone this github repository to your local and `cd` to it
2. Run following command to install dependencies and run development server : 
```bash
npm install
```
3. Setup `.env.local` file in following format:
```bash
DATABASE_URL = mongoDB-URI
NEXTAUTH_SECRET = ""
SDK_KEY = zoom_web_sdk_key
SDK_SECRET = zoom_web_secret
```
4. Run following command to generate [NEXTAUTH_SECRET](https://next-auth.js.org/configuration/options#nextauth_secret) hash
```bash
openssl rand -base64 32
```
5. Run following command to run development server : 
```bash
npm run dev
```
6. Open [http://localhost:3000](http://localhost:3000) with your browser to see the app.

---

## 🌲 **Project tree**
```text
.
├── app
│   ├── (guest_route)
│   ├── (private_route)
│   │   ├── meeting
│   │   ├── layout.tsx
│   │   └── zoom
│   ├── api
│   │   ├── auth
│   │   │   ├── [...next_auth]
│   │   │   └── users
│   │   └──  zoom
│   ├── sign-up
├── components
│   ├── Alert.tsx
│   ├── AuthProfileMenu.tsx
│   ├── AuthProvider.tsx
│   └── Navbar.tsx
├── lib
│   └── db.ts
├── models
│   └── userModel.ts
└── next.config.js

```

---

## 🌲 **Screenshots**
- Home Page
  image

- Sign Up Page
  image

- Start Meeting Page
  image

- Zoom Meeting Page
  image

### CODE REVIEW

**Comment by H4rsh4nk** [comment]
Hi @Shaomei, I have created the pull request. Can you please review it?

**Comment by Shaomei** [comment]
Thank you @H4rsh4nk! This is really cool.
Let me invite @blickly for a more thorough review!

**Review by blickly — COMMENTED** [review]
At a high level, I often find it useful to separate out the code autogenerated from a tool from the code that you hand edited into separate commits.

This not only makes reviewing easier (generally we care more about the hand-written code), but it also makes it easier to find the code you wrote in the commit history since you can more easily skip over the tooling-generated commits.

**Comment by H4rsh4nk** [comment]
Closing this PR and generating new PR with separate commits for autonomous code and edit code.

**Pull request closed without merging**
